# Workflow to build your reading-list with ResearchPocket
# and deploy them to Github Pages
name: Deploy Static site

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

# Alright, let's do it!
jobs:
  web:
    name: Build and deploy site and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest release tag
        id: get_release_tag
        run: |
          tag=$(curl -s https://api.github.com/repos/KorigamiK/ResearchPocket/releases/latest | jq -r .tag_name)
          echo "::set-output name=tag::$tag"

      - name: Download the binary
        run: |
          release_url='https://github.com/KorigamiK/ResearchPocket/releases/download'
          wget "${release_url}/${{ steps.get_release_tag.outputs.tag }}/research-linux-amd64"
          chmod +x research-linux-amd64

      - name: Initialize and fetch from Pocket
        run: |
          ./research-linux-amd64 init .
          ./research-linux-amd64 pocket fetch
        env:
          POCKET_CONSUMER_KEY: ${{ secrets.POCKET_CONSUMER_KEY }}
          POCKET_ACCESS_TOKEN: ${{ secrets.POCKET_ACCESS_TOKEN }}

      - name: Generate build
        run: ./research-linux-amd64 generate --download-tailwind ./build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
